== The story behind this solution pattern

The solution pattern is backed by the story of a retail store that has been active in the market for more than fifteen years. This retail store uses a single application to manage the `inventory`, `catalog` and `sales` during their daily operations.

[quote, Alex Tizon - CEO, About company current situation]
We are a leading retail store acting in the market for over 15 years. We managed to start digital technologies adoption many years ago by acquiring a solution for our inventory and sales registrations. Our biggest challenge is to join competition with high-tech competitors.

Here are some characteristics of the existing technology stack:

- The technology has been acquired many years ago, and no source code is available. 
- The application, application server and databases are installed and running in an on premise environment.
- There are domain experts who know how to keep the inventory and catalog list updated.
- There are operations running 24/7 using the sales application, stopping the application impacts the money income directly.

It's getting hard to compete with more high-tech companies, but the technical team does not have the required skills to boostrap the adoption of cloud-native technologies to enhance the organization online services.

[quote, Avery Smith- CTO, On modernization goals]
Our first step into modernization is developing a new cashback system for our customers. Adding to that, our current service lacks good searching capabilities so we need better ways for customers to find what they need.

[discrete]
include::partials/_01-story-goals.adoc[]

include::partials/_01-solution-summary.adoc[]

