=== Story Goals

To get started, the business and technical executives came up with initial goals to be achieved as a first step towards the organization modernization:

The Cashback Wallet Functionality::
- Customers should receive a percentage of their purchases as cashback.
- All the earned cashback is now part of the Cashback Wallet.
- With this, upcoming purchases can be paid either with the customer money or using available cashback in the customer Cashback Wallet.
- The customer should be able to check all transaction history including earned cashback and spent cashback
- New services and technologies must easily fit in cloud environments as we seek to move forward with clo adoption.

Enhanced search capabilities::
- Customers should be able to easily search for what they need;
- They should be able to search by part or all of the product name.
- The operations should still be able to use the legacy application to maintain the catalog and this data should benefit from the enhanced search capabilities.
- The new solution should be able to provide to technical team metrics about the search, like query latency and  request rate;
- If a new tool is used, we want to be able to choose where to deploy it - we want to be free of vendor lock-in.

